apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: solvency-cert
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containers:
      - image: ghcr.io/troymork/solvency-agent:latest
        env:
        - name: ROLE
          value: "cert"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 1
