apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: solvency-n8n
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - image: n8nio/n8n:1.79.3
        env:
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "https"
        - name: N8N_ENCRYPTION_KEY
          value: "change-me-please"
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          value: "kyrios"
        - name: N8N_BASIC_AUTH_PASSWORD
          value: "change-me-please"
        - name: GENERIC_TIMEZONE
          value: "America/Los_Angeles"
        ports:
        - containerPort: 5678
        resources:
          limits:
            memory: 512Mi
            cpu: 1
