services:
  n8n:
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_PERSONAL_ACCESS_TOKENS_ENABLED=true
      - N8N_BASIC_AUTH_ACTIVE=false
